[app]
header = "ZCZC-EAS-INT-042003+0000-2330217-BUG/HTTP-"
footer = "NNNN"
tone_seconds = 8.0
siren_placement = "after"
siren_goarounds = 16
siren_length = 4
use_file = false
use_siren = true
potato_siren = false
external_target = ""
voice_text = "pre-bed checklist"

[same]
event = "INT - INT (Internal Test)"
county_keys = ["000000"]
duration = "0000"
originator = "WXR"
station_id = "BUG/HTTP"

[auto]
event_codes = []
callsign = "BUG/HTTP"
counties = []
weather_text = true
alert_text_template = "HAZ...{hazard} HAIL {hail} SRC...{source}"
